
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class UndeployProcedureParameters {
    /**
    * Label: Use Default Artifacts, type: checkbox
    */
    boolean useDefaultArtifacts
    /**
    * Label: Deployment Artifacts, type: textarea
    */
    String deploymentArtifacts

    static UndeployProcedureParameters initParameters(StepParameters sp) {
        UndeployProcedureParameters parameters = new UndeployProcedureParameters()

        def useDefaultArtifacts = sp.getParameter('useDefaultArtifacts').value == "true"
        parameters.useDefaultArtifacts = useDefaultArtifacts

        def deploymentArtifacts = sp.getParameter('deploymentArtifacts').value
        parameters.deploymentArtifacts = deploymentArtifacts

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 128a0c2ad42c68b484aabc003a0157da ===
