
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class UndeployProcedureParameters {
    /**
    * Label: Deployment Artifacts, type: textarea
    */
    String deploymentArtifacts

    static UndeployProcedureParameters initParameters(StepParameters sp) {
        UndeployProcedureParameters parameters = new UndeployProcedureParameters()

        def deploymentArtifacts = sp.getRequiredParameter('deploymentArtifacts').value
        parameters.deploymentArtifacts = deploymentArtifacts  ?: """{
  "deploymentSystem": "Some3rdPartyTool",
  "deploymentUrl": "https://repository.sonatype.org/service/local/repositories/atlassian-maven-external/content/org/apache/tomcat/apache-tomcat/",
  "artifacts": [
      "artifact1",
      "artifact2",
      "artifact3",
      "artifact1x",
      "artifact2x",
      "artifact3x"
  ]
}
"""

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 65ef5cbf0a8b01dda2ece9c58fd00f29 ===
