pluginInfo:
  pluginName: 'BringYourOwnDeployerPlugin'
  version: '0.0.2'
  description: 'Demo Plugin to demonstrate the third party inventory interface'
  author: 'CloudBees'
  supportUrl: 'https://github.com/electric-cloud-community'
  category: 'Utilities'
  shell: 'ec-groovy'
  repositoryUrl: 'https://github.com/electric-cloud-community/BringYourOwnDeployerPlugin'
  label: 'Bring Your Own Deployer Plugin (Demo)'
  detailedDescription: |
    Demo plugin to demonstrate the third-party inventory interface

procedures:
-
  name: 'Deploy Procedure'
  description: 'Example of deploy procedure that sets required job properties for third-party artifacts'
  hasConfig: false
  parameters:
  - 
    name: deploymentArtifacts
    documentation: JSON input in valid format with information about third-party artifacts.
    required: false
    type: textarea
    label: Deployment Artifacts
    value: |
      {
        "deploymentSystem": "Some3rdPartyTool",
        "deploymentUrl": "https://repository.sonatype.org/service/local/repositories/atlassian-maven-external/content/org/apache/tomcat/apache-tomcat/",
        "artifacts": [
          {
            "artifactName": "artifact1",
            "artifactVersion": "1.2.5",
            "artifactUrl": "https://repository.sonatype.org/service/local/repositories/atlassian-maven-external/content/org/apache/tomcat/apache-tomcat/10.0.14-atlassian-hosted/apache-tomcat-10.0.14-atlassian-hosted.pom",
            "additionalDetails": {
              "deploymentTargets": "target1, target2",
              "detail1": "value1",
              "detail2": "value2"
            }
          },
          {
            "artifactName": "artifact2",
            "artifactVersion": "3.2.6",
            "artifactUrl": "https://repository.sonatype.org/service/local/repositories/atlassian-maven-external/content/org/apache/tomcat/apache-tomcat/10.0.14-atlassian-hosted/apache-tomcat-10.0.14-atlassian-hosted.pom",
            "additionalDetails": {
              "deploymentTargets": "target2, target4",
              "detail1": "value1",
              "detail2": "vFalue2"
            }
          }
        ]
      }
-
  name: 'Undeploy Procedure'
  description: 'Any undeploy procedure'
  hasConfig: false
  parameters:
  -
    name: deploymentArtifacts
    documentation: JSON input in valid format with information about third-party artifacts.
    required: false
    type: textarea
    label: Deployment Artifacts
    value: |
      {
        "deploymentSystem": "Some3rdPartyTool",
        "deploymentUrl": "https://repository.sonatype.org/service/local/repositories/atlassian-maven-external/content/org/apache/tomcat/apache-tomcat/",
        "artifacts": [
            "artifact1",
            "artifact2",
            "artifact3",
            "artifact1x",
            "artifact2x",
            "artifact3x"
        ]
      }
